### ISSUE TITLE
unable to parse .jpg file

### ISSUE THREAD

**Issue by JEnIUS85** [ptigas/simple-captcha-solver#14]
Hi ptigas 

i am testing your python code against my captcha image. I have made sure that i am creating a 5 digit Hexadecimal captcha and saving it in .jpg format.

Moreover, i have used "monospace" font. But code is failing to capture.

To test, i have inserted following line of code in test.py:
self.assertEqual(decoder('1.jpg'), '568ee')

1.jpg is attached for your reference ..

Please send your response at the earliest.

![1](https://cloud.githubusercontent.com/assets/12089890/24255516/bf45c888-100b-11e7-9440-a942630158f2.jpg)

**Comment by ptigas** [comment]
Hi, have you created your own mask using the same font as well ?

**Comment by JEnIUS85** [comment]
thx for ur response. 

ah, regarding "have you created your own mask using the same font as well ?" -- i have used simpleCaptcha library ,written in java, to create the image and defined font to be monospace. But from your response, I believe there is more to it.

if you can tell how you have created the test.jpg files then that will be better. it will help me to understand the login in python code much better..

**Comment by ptigas** [comment]
The important bit is to create a mask like this https://raw.githubusercontent.com/ptigas/simple-captcha-solver/master/letters.bmp. Please read the writeup, I explain the process there.

Regarding the `test.jpg` it was produced by a php library that i don't have access to it anymore.

**Comment by JEnIUS85** [comment]
ok
