### ISSUE TITLE
Can I Solve These With Your Solution?

### ISSUE THREAD

**Issue by adbanaei** [ptigas/simple-captcha-solver#21]
![Captcha1](https://user-images.githubusercontent.com/48990617/212571562-315557be-c287-42d6-bc42-5326a171b3a8.png)
![Capcha2](https://user-images.githubusercontent.com/48990617/212571569-9dc8f9d9-a403-43de-b911-78a879030b24.png)

**Comment by hacknapier** [comment]
Try it https://rapidapi.com/flyCaptcha/api/flycaptcha
@adbanaei @arkrwn @mohan3d @ptigas @florenthemmi
