### ISSUE TITLE
Same results is returned

### ISSUE THREAD

**Issue by ezgikaysi** [ptigas/simple-captcha-solver#4]
Hi,

 I tried your code with  test.jpg, test2.jpg and other captcha images but it returns only 14d86. I think code is not working correctly.

**Comment by Pr0xy671** [comment]
How do you use the scripts?

**Comment by mohan3d** [comment]
@Pr0xy671 
`python pyocr.py your_image_path`

ex: `python pyocr.py test.jpg `

**Comment by Jack614** [comment]
I have the same question,the command is : python pyocr.py test2.jpg. the return is 14d86.

**Comment by mohan3d** [comment]
@Jack614 try [this](https://github.com/ptigas/simple-captcha-solver/pull/5)

**Comment by Jack614** [comment]
@mohan3d it works,thanks :)

**Comment by ezgikaysi** [comment]
Yes it worked for me too. Thanks @mohan3d

**Comment by ptigas** [comment]
@mohan3d thanks for the fix :)

**Comment by mohan3d** [comment]
@Jack614 , @ezgikaysi , @ptigas  You're welcome :)
