### ISSUE TITLE
Error at runtime

### ISSUE THREAD

**Issue by thinkpozzitive** [ptigas/simple-captcha-solver#6]
I'm getting the following error when trying to run the example:

```
Traceback (most recent call last):
  File "crack_test.py", line 72, in <module>
    pix = im.getpixel((y,x))
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1205, in getpixel
    self.load()
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 760, in load
    self.im.putpalette(*self.palette.getdata())
ValueError: unrecognized raw mode
```

I'm using Python 2.7.11 and Pillow 3.3.1

Thoughts on how to fix this?

**Comment by mohan3d** [comment]
I have same configuration (python 2.7.11, pillow 3.3.1).
![2016-08-31_23-18-32](https://cloud.githubusercontent.com/assets/14618484/18146803/f39016dc-6fd1-11e6-95b8-51b91a74699b.jpg)

but It worked for me, are you sure you run pyocr.py against test.jpg or test2.jpg ?

**Comment by thinkpozzitive** [comment]
Sorry my bad, had multiple examples in one dir and I mismatched one one of the files I was using.

Your example is working as expected.

Thanks.
